//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_RegistrationForm24Feb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgrammingLanguage
    {
        public int ProgID { get; set; }
        public string Programming_Name { get; set; }
        public int IsThere { get; set; }
    }
}
