//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_RegistrationForm24Feb.Models
{
    using System;
    using System.Web;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Registration
    {
        public int ID { get; set; }
        public string First_Name { get; set; }
        public string Second_Name { get; set; }

        [Required]
        public string Email_ID { get; set; }

        [Required]
        public string Password { get; set; }
        
        public string State { get; set; }
        public string Country { get; set; }
       
        [DisplayName("Choose Image")] 
        [Required]
        public string Profile_Pic { get; set; }

        [Required]
        public string Gender { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
    }
}
