//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_RegistrationForm24Feb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int ID { get; set; }
        public string First_Name { get; set; }
        public string Second_Name { get; set; }
        public string Email_ID { get; set; }
        public string Password { get; set; }
        public string Profile_Pic { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
    }
}
